# Netlify configuration for Vite + React app
# Docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  publish = "dist"

# Local Netlify dev (optional)
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Single Page App routing: serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional security headers (basic hardening)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Tip: Set your environment variables in Netlify UI
# Site settings → Build & deploy → Environment → Environment variables
# Add these keys with your values so Vite can use them at build time:
#  - VITE_EMAILJS_SERVICE_ID
#  - VITE_EMAILJS_TEMPLATE_ID
#  - VITE_EMAILJS_PUBLIC_KEY
